// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHj6mi5APPF6GjpCgLzjmwcfK-VveQWcc',
    appId: '1:802638932962:web:18ad99f5655cf65cb667bb',
    messagingSenderId: '802638932962',
    projectId: 'storemate-saas-app',
    authDomain: 'storemate-saas-app.firebaseapp.com',
    storageBucket: 'storemate-saas-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0lTE5cbcNpdh93ohFNcpHq8dKQSj83E',
    appId: '1:802638932962:android:d61c962906e92fb5b667bb',
    messagingSenderId: '802638932962',
    projectId: 'storemate-saas-app',
    storageBucket: 'storemate-saas-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjO4JtcJULttJ_Ksm-Hhgkr3dx4iUYKrY',
    appId: '1:802638932962:ios:4b21dbba33af0a82b667bb',
    messagingSenderId: '802638932962',
    projectId: 'storemate-saas-app',
    storageBucket: 'storemate-saas-app.firebasestorage.app',
    iosBundleId: 'com.StoreMate.storemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjO4JtcJULttJ_Ksm-Hhgkr3dx4iUYKrY',
    appId: '1:802638932962:ios:4b21dbba33af0a82b667bb',
    messagingSenderId: '802638932962',
    projectId: 'storemate-saas-app',
    storageBucket: 'storemate-saas-app.firebasestorage.app',
    iosBundleId: 'com.StoreMate.storemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHj6mi5APPF6GjpCgLzjmwcfK-VveQWcc',
    appId: '1:802638932962:web:97994a8f0049db61b667bb',
    messagingSenderId: '802638932962',
    projectId: 'storemate-saas-app',
    authDomain: 'storemate-saas-app.firebaseapp.com',
    storageBucket: 'storemate-saas-app.firebasestorage.app',
  );
}
